### ISSUE TITLE
Any plans for supporting status?

### ISSUE THREAD

**Issue by blublinsky** [novakov-alexey/freya#16]
One of the things that was missing from Java Abstract operator was support for status. I am not sure its implemented in Fabric-8, but last time I checked was about 6 month ago. Are you planning to support status?

**Comment by novakov-alexey** [comment]
@blublinsky Thank you for your question. 
Fabric-8 client now supports Status Update since yesterday release :-) 
https://github.com/fabric8io/kubernetes-client/issues/1548

Yes, I can add this feature now to Freya. Quick idea to let the controller to return `F[Option[Status]]` instead of `F[Unit]`. That means, the returned Status will be used to set the CR object status and applied by Freya automatically. 

Do you have any particular use-case or requirements as for the status feature that may help to design this better?

**Comment by blublinsky** [comment]
Thanks Alexey, 
I do not have any specific use case in mind, but F[Option[Status]] seems like a much better option. In Flink implementation, for example, I was thinking about returning back pods statuses and URL of the master, So setting Status directly in CR would give you the best flexibility.

**Comment by novakov-alexey** [comment]
Understood, thanks for feedback. Let's see if this feature is easy to implement.

**Comment by novakov-alexey** [comment]
@blublinsky Status feature has been already added. However, its behaviour is quite strange. I am not sure if it is fabric8 issue or my kubernetes version has some bug in status update. I am trying to clarify expected behaviour here: https://github.com/fabric8io/kubernetes-client/issues/1548#issuecomment-579470177.
Anyway, latest Freya version can already update CR status, the issue itself is a side-effect `Modify` event sent right after the status update. It should not be a problem when operator is idempotent.
